### ISSUE TITLE
Live reload?

### ISSUE THREAD

**Issue by lapidus** [evocode/metalsmith-base#4]
Thank you for a great starter kit. How would I add live reload to it? Thanks!

**Comment by patrickheeney** [comment]
There is currently a [gulp watch](https://github.com/evocode/metalsmith-base/blob/3a96ad166c771a34246f156ffbf6725b8f9ab515/gulpfile.js#L149) command that rebuilds on assets or metalsmith changes. As far as browsersync or similar tools, they would likely have to be added into the gulp process somewhere.

**Comment by lapidus** [comment]
Thanks!
