### ISSUE TITLE
Proper way to include JS and CSS libs?

### ISSUE THREAD

**Issue by lapidus** [evocode/metalsmith-base#5]
I would like to make use of for example:
https://github.com/IanLunn/Hover
https://github.com/mbostock/d3

For the first one I would like to make use of the bundled scss files and for the second one only the plain min.js file. Should I add bower to the mix or is this somehow supposed to be taken care of by npm or webpack? Thanks and sorry if the question is too basic ...

**Comment by patrickheeney** [comment]
For the styles, I would use npm to get the packages locally and them import them like I do bootstrap in [app.scss](https://github.com/evocode/metalsmith-base/blob/master/styles/app.scss). 

As far as the scripts, you should be able to add them to webpack [here](https://github.com/evocode/metalsmith-base/blob/master/gulpfile.js#L116) after installing from npm to have them be compiled with the vendor.js files.

**Comment by patrickheeney** [comment]
There is also some other tips here for d3: http://fengshuo.co/2015/06/27/use-webpack-with-d3-dashboard-pages/

**Comment by lapidus** [comment]
Thank you, really helpful!
Got both the CSS and JS to work nicely now.
