### ISSUE TITLE
Use relative paths?

### ISSUE THREAD

**Issue by lapidus** [evocode/metalsmith-base#7]
I would like to host my site in a subfolder (for example Github Pages: http://username.github.io/project/), where this absolute syntax would not work:
<link rel="stylesheet" type="text/css" href="/assets/app.css">

How can I make it work with root on localhost but append "project" (in this case) on remote?

Thanks!

**Comment by patrickheeney** [comment]
You can adjust the build script to move the contents of the build dir to your subfolder before you commit to git. Probably something like this:

```
...
mv $TMP_FOLDER/.git build/.git
rm -rf $TMP_FOLDER
mv * project/
```
